version: "2.2"
services:
  web:
    build: .
    container_name: "ldeng_jupyter"
    user: 6079:500
    ports:
      - 6079:8888
    volumes:
      - /data/ldeng:/home/jovyan
    cpu_count: 64
    mem_limit: 256gb
